;; this file should be probably automatically generated by reflection

(put 'with-gensyms 'scheme-indent-function 1)
(put 'handler-case 'scheme-indent-function 1)
(put 'handler-bind 'scheme-indent-function 1)
(put 'restart-case 'scheme-indent-function 1)
(put 'restart-bind 'scheme-indent-function 1)
(put 'with-gensyms 'scheme-indent-function 1)

(put 'catch 'scheme-indent-function 1)
(put 'loop 'scheme-indent-function 0)