/* 
 * This file is automatically generated from UnicodeData.txt
 * using udata-gen.c
 */

#include <stdint.h>
typedef struct udata_entry_t{
  char category[3];
  int32_t upper_offset;
  int32_t lower_offset;
  int32_t title_offset;
} udata_entry_t;

#define FIRST_SIZE 4352
#define SECOND_SIZE 256

#define UDATA_ENTRY(n) \
   (dfsch__udata_properties[dfsch__udata_tables[dfsch__udata_table_type[((n) / SECOND_SIZE) % FIRST_SIZE]][(n) % SECOND_SIZE]])
#define UDATA_MAX 1114112
extern unsigned char dfsch__udata_table_type[];
extern unsigned char dfsch__udata_tables[][256];
extern udata_entry_t dfsch__udata_properties[];